replicaCount: 2

image:
  repository: hashicorp/http-echo
  tag: "1.0"

responseText: "Hello from backend"

containerPort: 5678
servicePort: 80

resources:
  requests:
    cpu: 50m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 64Mi
