config {
  format = "compact"
}

plugin "terraform" {
  enabled = true
  preset  = "recommended"
}

# These modules are always run through Terragrunt, which generates a single
# shared versions.tf (see deploy/terragrunt/root.hcl's "versions" generate
# block) into every unit's working directory at plan/apply time. Adding a
# versions.tf directly to a module would collide with that generated file
# (Terraform allows exactly one required_providers block per module), so
# these two rules are disabled rather than "fixed" by reintroducing that
# conflict. Verified live: adding one broke `terragrunt plan` with
# "already exists and was not generated by terragrunt".
rule "terraform_required_version" {
  enabled = false
}

rule "terraform_required_providers" {
  enabled = false
}
